#include "services/export/ObjExporter.h"

#include <filesystem>
#include <fstream>

namespace fs = std::filesystem;

namespace beamlab::services::export_ {

ExportResult ObjExporter::exportData(
    const storage::IStorageBackend& storage,
    const analysis::AnalysisResult& result,
    const fs::path& outputPath,
    ExportProgressCallback onProgress)
{
    if (onProgress) onProgress(0.0f, "Preparing OBJ export");

    auto objPath = outputPath;
    if (fs::is_directory(outputPath)) {
        objPath = outputPath / "envelope_mesh.obj";
    }

    std::ofstream out(objPath);
    if (!out.is_open()) {
        return ExportResult{false, "Cannot write " + objPath.string(), objPath, 0};
    }

    // Write OBJ header with metadata.
    out << "# BeamLabStudio envelope mesh\n";
    out << "# Generated by ObjExporter\n";
    out << "# Analysis success: " << (result.success ? "true" : "false") << "\n";
    out << "# Engines: ";

    bool first = true;
    for (const auto& [name, _] : result.engineResults) {
        if (!first) out << ", ";
        out << name;
        first = false;
    }
    out << "\n";
    out << "# Duration: " << result.duration.count() << " ms\n";
    out << "\n";

    // Write placeholder geometry.
    out << "# --- Vertex data ---\n";
    out << "v 0.0 0.0 0.0\n";
    out << "v 1.0 0.0 0.0\n";
    out << "v 0.0 1.0 0.0\n";
    out << "v 0.0 0.0 1.0\n";

    out << "# --- Face data ---\n";
    out << "f 1 2 3\n";
    out << "f 1 3 4\n";

    // TODO: Extract actual vertex/face data from result metrics.
    //  Expected format in engine metrics:
    //    "mesh_vertices": [[x1,y1,z1], [x2,y2,z2], ...]
    //    "mesh_faces":    [[i1,j1,k1], [i2,j2,k2], ...]

    uint64_t bytesWritten = static_cast<uint64_t>(out.tellp());
    out.close();

    if (onProgress) onProgress(1.0f, "OBJ export complete (stub)");

    return ExportResult{true, std::nullopt, objPath, bytesWritten};
}

} // namespace beamlab::services::export_
